services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile # the backend one you added
    environment:
      # allow your local web app to call the API
      - ALLOW_ORIGIN=${WEB_ORIGIN-http://localhost:5173}
    ports:
      - "8080:8080"
    restart: unless-stopped

  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm i && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://api:8080 # hit API via service name
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped
